version: "3"

services:
  rest:
    image: mhart/alpine-node:8
    command: npm run dev
    restart: on-failure
    working_dir: /app
    volumes:
      - ./rest:/app
    ports:
      - "3001:3001"
    links: 
      - 'mongo'
    depends_on:
      - 'mongo'
    networks:
      - backend

  graphql:
    image: mhart/alpine-node:8
    command: npm run dev
    restart: on-failure
    working_dir: /app
    volumes:
      - ./graphql:/app
    ports:
      - "3002:3002"
    links: 
      - 'mongo'
    depends_on:
      - 'mongo'
    networks:
      - backend
    
  prisma:
    image: prismagraphql/prisma:1.34
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            database: conduit_nodejs
            uri: mongodb://mongo/conduit_nodejs
    links: 
      - 'mongo'
    depends_on:
      - 'mongo'
    networks:
      - backend

  prismabackend:
    image: mhart/alpine-node:8
    command: sh -c "npm run deploy && npm run dev"
    working_dir: /app
    volumes:
      - ./prisma:/app
    ports:
      - "3003:3003"
    links: 
      - 'prisma'
      - 'mongo'
    depends_on:
      - 'prisma'
      - 'mongo'
    networks:
      - backend

  mongo:
    image: mvertes/alpine-mongo
    ports:
      - '27017:27017'
    volumes:
      - /var/lib/mongodb:/data/db
    networks:
      - backend

networks:
  backend:
