version: "3"

services:
  rest:
    image: mhart/alpine-node:8
    command: npm run dev
    working_dir: /app
    volumes:
      - ./rest:/app
    ports:
      - "3001:3001"
    networks:
      - backend

  graphql:
    image: mhart/alpine-node:8
    command: npm run dev
    working_dir: /app
    volumes:
      - ./graphql:/app
    ports:
      - "3002:3002"
    networks:
      - backend

  mongo:
    image: mvertes/alpine-mongo
    ports:
      - '27017:27017'
    volumes:
      - /var/lib/mongodb:/data/db
    networks:
      - backend

networks:
  backend: