version: "3.0"

services:

  api:
    image: alpine-node:8
    command: npm start
    working_dir: /app
    volumes:
      - ".:/app"
    env_file: docker-compose.env
    environment:
      NODE_ENV: production
      SERVICES: api
      PORT: 3000
    links:
      - redis
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"   
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"
    #deploy:
    #  replicas: 2

  articles:
    image: alpine-node:8
    command: npm start
    working_dir: /app
    volumes:
      - ".:/app"
    env_file: docker-compose.env
    environment:
      NODE_ENV: production
      SERVICES: articles
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
    #deploy:
    #  replicas: 2

  adventures:
    image: alpine-node:8
    command: npm start
    working_dir: /app
    volumes:
      - ".:/app"
    env_file: docker-compose.env
    environment:
      NODE_ENV: production
      SERVICES: adventures
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
    #deploy:
    #  replicas: 2

  comments:
    image: alpine-node:8
    command: npm start
    working_dir: /app
    volumes:
      - ".:/app"
    env_file: docker-compose.env
    environment:
      NODE_ENV: production
      SERVICES: comments
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
    #deploy:
    #  replicas: 2

  favorites:
    image: alpine-node:8
    command: npm start
    working_dir: /app
    volumes:
      - ".:/app"
    env_file: docker-compose.env
    environment:
      NODE_ENV: production
      SERVICES: favorites
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
    #deploy:
    #  replicas: 2

  follows:
    image: alpine-node:8
    command: npm start
    working_dir: /app
    volumes:
      - ".:/app"
    env_file: docker-compose.env
    environment:
      NODE_ENV: production
      SERVICES: follows
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
    #deploy:
    #  replicas: 2

  users:
    image: alpine-node:8
    command: npm start
    working_dir: /app
    volumes:
      - ".:/app"
    env_file: docker-compose.env
    environment:
      NODE_ENV: production
      SERVICES: users
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
    #deploy:
    #  replicas: 2

  redis:
    image: redis:alpine

  mongo:
    image: mvertes/alpine-mongo
    volumes:
      - /var/lib/mongodb:/data/db

  traefik:
    image: traefik:v1.7
    # command: --web --docker --docker.domain=docker.localhost --logLevel=INFO --docker.exposedbydefault=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
